apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
        - name: db-pod
          image: postgres:15-alpine
          env:
            - name:  'POSTGRES_USER'
              value: 'postgres'
            - name:  'POSTGRES_PASSWORD'
              value: 'postgres'
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: db-data-pvc
