apiVersion: v1
kind: PersistentVolume
metadata:
  name: healthcheck-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/healthchecks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthcheck-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi