apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - db-data-PV.yml
  - db-data-PVC.yml
  - db-deployment.yml
  - db-service.yml
  - redis-deployment.yml
  - redis-service.yml
  - result-deployment.yml
  - result-service.yml
  - seed-job.yml
  - vote-deployment.yml
  - vote-HPA.yml
  - vote-service.yml
  - worker-deployment.yml


configMapGenerator:
  - name: db-config
    envs:
      - db-config.env
  - name: result-configmap
    envs:
      - result-config.env
