apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  selector:
    app: result
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer 
