apiVersion: v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
spec:
  containers:
    - image: result:latest
      name: result
      ports:
        - containerPort: 4000
      env:
        - name: PORT
          value: "4000"