- name: Stream PostgreSQL DB backup to localhost
  hosts: localhost
  gather_facts: no
  vars:
    db_user: postgres
    db_name: postgres
    pg_password: "postgres"
    remote_user: root
    remote_pwd: mdp
    backup_filename: "backup.sql"
    inventory_hostname: "{{ hostvars['vm1']['ansible_host'] }}"
  tasks:
    - name: Stream DB backup from remote server to localhost
      shell: >
        sshpass -p {{remote_pwd}}
        ssh -o StrictHostKeyChecking=no {{ remote_user }}@{{ inventory_hostname }}
        "sudo -u {{ db_user }} PGPASSWORD={{ pg_password }} pg_dump -U {{ db_user }} {{ db_name }}" > {{ backup_filename }}
      delegate_to: localhost
      environment:
        PGPASSWORD: postgres

- name: Restore dump to destination host
  hosts: vm2
  gather_facts: no
  vars:
    local_backup_path: "./backup.sql"
    remote_dump_path: "/tmp/backup_{{ ('pipe', 'date +%Y%m%d%H%M%S') }}.sql"
  tasks:
    - name: Copy dump file from localhost to destination host
      ansible.builtin.copy:
        src: "{{ local_backup_path }}"
        dest: "{{ remote_dump_path }}"
        force: true
