- name: Stream PostgreSQL DB backup to localhost
  hosts: vm2
  gather_facts: no
  vars:
    db_user: postgres
    db_name: postgres
    pg_password: "postgres"
    remote_user: root
    remote_pwd: mdp
    backup_filename: "/tmp/backup.sql"
    inventory_hostname: "{{ hostvars['vm1']['ansible_host'] }}"
  tasks:
    - name: Stream DB backup from remote server to localhost
      shell: >
        sshpass -p {{remote_pwd}}
        ssh -o StrictHostKeyChecking=no {{ remote_user }}@{{ inventory_hostname }}
        "sudo -u {{ db_user }} PGPASSWORD={{ pg_password }} pg_dump -U {{ db_user }} {{ db_name }}" > {{ backup_filename }}
      delegate_to: localhost
      environment:
        PGPASSWORD: postgres
    - name: Restore database from dump
      ansible.builtin.shell: |
        PGPASSWORD={{ pg_password }} psql -U {{ pg_user }} -d {{ db_name }} -f {{ remote_dump_path }}
      args:
        executable: /bin/bash
      become: true
      become_user: postgres
