- name: Install postgresql-15
  ansible.builtin.apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Install python3-psycopg2
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Start service postgres
  service:
    name: postgresql
    state: started

- name: Create a new database with name "postgres"
  community.postgresql.postgresql_db:
    name: postgres
    comment: The postgre DB
  become: true
  become_user: postgres

- name: Create user postgre with password
  community.postgresql.postgresql_user:
    login_db: postgres
    name: postgres
    password: postgres
  become: true
  become_user: postgres

- name: Grant privs to postgre
  community.postgresql.postgresql_privs:
    login_db: postgres
    state: present
    privs: all
    type: database
    roles: CURRENT_USER
  become: true
  become_user: postgres

- name: Get pg_hba.conf path
  command: psql -t -P format=unaligned -c "SHOW hba_file;"
  register: pg_hba_path
  become: true
  become_user: postgres

- name: Allow postgres user to connect via md5
  community.postgresql.postgresql_pg_hba:
    dest: "{{ pg_hba_path.stdout | trim }}"
    contype: host
    users: postgres
    databases: all
    address: all
    method: md5
    state: present

- name: Set listen_addresses to 0.0.0.0
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "0.0.0.0"
  become: true
  become_user: postgres

- name: Restart service postgresql
  ansible.builtin.systemd:
    name: postgresql.service
    state: restarted
